name: personality
description: Personality test app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  flutter_native_splash: ^2.1.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  json_annotation: ^4.5.0
  dio: ^4.0.6
  http_mock_adapter: ^0.3.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons_maker: ^0.10.2
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  flutter_gen_runner: ^4.1.6

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  color: "#00012a"
  image: assets/launcher_icon.png
  android_gravity: fill
  fullscreen: true
  android_12:
    color: "#00012a"
    image: assets/launcher_icon.png
    android_gravity: fill
    fullscreen: true
